# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb0580698a4a5a9b80c955906ee9929d5ac931cf13cd191f3e7a5dee1e2abb47a2c4301e70635eecdab3f4cfc570d4d36339a7691b189338ffc5efba2193b6e7

test:
  secret_key_base: f1fba7db66d7f7ce42ea0f8f82509e87212773e4840f058a09f2b97479ab45ee28b1aba89cef62ce95f5c966ca18eb5cb1f1f1f870526174de05a35312cf47c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
